import { ScanText, Smartphone, Zap } from 'lucide-react'
import { Button } from '@/components/ui/button'

export function ProfileOCRPanel({ state, format, reading, canRead, canDecide, onRead, onDecide, onCollect, onInspect, native, connected, mode, onMode, onSource, progress, onStop, captured, onReset, nextProfile }: { state: string; format: 'text' | 'json'; reading: boolean; canRead: boolean; canDecide: boolean; onRead: () => void; onDecide: () => void; onCollect: () => void; onInspect?: () => void; native: boolean; connected: boolean; mode: 'immediate' | 'full'; onMode: (mode: 'immediate' | 'full') => void; onSource: () => void; progress: string; onStop: () => void; captured: (string | undefined)[]; onReset: () => void; nextProfile?: { name: string; age: number } }) {
  let profile: { name?: string; age?: number; location?: string; distance_km?: number; photo_count?: number; bio?: string; interests?: string[] } | undefined
  if (format === 'json') { try { profile = JSON.parse(state) } catch { /* State validation reports invalid JSON when submitted. */ } }
  return <section className="profile-ocr-panel" aria-label="Profile OCR">
    <div className="profile-capture-options"><button className="profile-source" onClick={onSource} disabled={reading}><Smartphone size={12} />{native ? 'Android accessibility' : 'Image OCR'}</button><div role="group" aria-label="Profile capture mode">{(['immediate', 'full'] as const).map(value => <button key={value} aria-pressed={mode === value} disabled={reading} onClick={() => onMode(value)}>{value === 'immediate' ? 'Immediate' : 'Full profile'}</button>)}</div></div>
    <div className="profile-ocr-toolbar"><span><ScanText size={12} />PROFILE TEXT</span><div><Button variant="ghost" size="xs" disabled={!canRead} onClick={onRead}>{reading ? 'Reading…' : 'Read text'}</Button><Button variant="secondary" size="xs" disabled={!canRead || !canDecide} onClick={onDecide}><Zap size={12} />Read + decide</Button><Button variant="ghost" size="icon-xs" aria-label="Collect Android profile" disabled={reading} onClick={onCollect}><Smartphone size={13} /></Button></div></div>
    {nextProfile && <div className="next-profile-detected" role="status">New profile · <strong>{nextProfile.name} {nextProfile.age}</strong></div>}
    <div className="profile-session-actions"><Button variant="outline" size="xs" disabled={reading || !canRead} onClick={onRead}>{nextProfile ? 'Read new profile' : 'Read next profile'}</Button><Button variant="ghost" size="xs" disabled={reading} onClick={onReset}>Reset profile</Button></div>
    {native && <div className="profile-read-progress" role="status"><span>{reading ? progress : connected ? 'Phone ready' : 'Connect Android to read the profile'}{reading && <small> · Scores follow the completed profile read.</small>}</span><Button variant="secondary" size="xs" disabled={!connected} onClick={onStop}>Cancel phone capture</Button></div>}
    {captured.length > 0 && <div className="profile-capture-gallery"><div className="profile-capture-count"><span>CAPTURED PHOTOS</span><strong>{captured.filter(Boolean).length}/{captured.length}</strong></div><div className="profile-capture-strip" aria-label="Captured profile photos">{captured.map((image, i) => <div key={i}>{image ? <img src={image} alt={`Captured photo ${i + 1}`} /> : <span>…</span>}<small>{i + 1}{image && ' ✓'}</small></div>)}</div></div>}
    {profile?.name ? <div className="profile-clean-preview"><div><strong>{profile.name} {profile.age}</strong>{profile.distance_km != null && <span>{profile.distance_km} km away</span>}{profile.photo_count != null && <span>{profile.photo_count} photos</span>}{profile.location && <span>{profile.location}</span>}{onInspect && <button onClick={onInspect}>Inspect text</button>}</div>{profile.interests?.length ? <p className="profile-interest-preview">{profile.interests.join(' · ')}</p> : null}{profile.bio && <p className="profile-bio-preview">{profile.bio}</p>}</div> : <p className="profile-ocr-hint">{native && mode === 'full' ? 'One read collects every photo and all expanded profile details.' : 'Read the current profile into State.'}</p>}
  </section>
}
